-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 24, 2021 at 05:12 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `posting`
--

CREATE TABLE `posting` (
  `id_thread` int(50) NOT NULL,
  `user_id` int(50) NOT NULL,
  `judul` varchar(200) NOT NULL,
  `konten` text NOT NULL,
  `kategori` varchar(50) NOT NULL,
  `thumb` varchar(50) NOT NULL,
  `tanggal_posting` timestamp NOT NULL DEFAULT current_timestamp(),
  `diubah` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `posting`
--

INSERT INTO `posting` (`id_thread`, `user_id`, `judul`, `konten`, `kategori`, `thumb`, `tanggal_posting`, `diubah`) VALUES
(30, 4, 'Inikah Tanggal Peluncuran Samsung Galaxy S21 FE? ', 'Sekian lama nasibnya tak kunjung jelas, kini tanda-tanda kehadiran <strong>Galaxy S21 FE</strong> (<em>Fan Edition</em>) kian menguat. Belakangan, berembus kabar yang mengungkap tanggal peluncuran ponsel versi \"murah\" dari lini Galaxy S21 ini. <br /><br />Salah satu kabar tersebut dibagikan oleh, Jon Prosser, seorang pembocor gadget kenamaan yang kerap membeberkan informasi terkait smartphone yang akan dirilis di pasaran. <br /><br />Melalui akun Twitter pribadinya dengan handle @jon_prosser, ia mengungkap detail informasi seputar tanggal peluncuran Galaxy S21 FE. <br /><br />Menurut Prosser, Samsung disinyalir akan mengumumkan kehadiran Galaxy S21 FE pada 3 Januari pukul 18.00 PST atau 4 Januari 09.00 pagi apabila dikonversi ke satuan Waktu Indonesia Bagian Barat (WIB). <br /><br />Meski demikian, waktu tersebut terlihat janggal karena tidak selaras dengan perkiraan mulainya sesi keynote Samsung di Customers Electronics Show (CES) 2022 yang akan dilaksanakan pada 4 Januari 2022 18.30 PST (sekitar 5 Januari 09.30 WIB). <br /><br />Sebelumnya, terdapat indikasi kuat yang menyebut bahwa informasi seputar Galaxy S21 FE akan diumumkan melalui acara pameran teknologi akbar, CES 2022 yang rencananya akan digelar 5-8 Januari 2022 di Las Vegas, Amerika Serikat. <br /><br />Selain membeberkan indikasi tanggal peluncuran perangkat, Prosser turut mengungkap jadwal penjualan perdana Galaxy S21 FE yang konon akan pada digelar pada 11 Januari 2022. Apabila mengacu pada posting awal yang diunggah Prosser, maka Galaxy S21 FE diduga akan dijual secara langsung tanpa harus didului sesi pemesanan awal (pre-order). \"Saya mendengar bahwa pengumuman untuk S21 FE telah dipindahkan ke Senin, 3 Januari @6 sore PST. <br /><br />Ketersediaan umum masih pada 11 Januari,\" tulis akun Twitter @jon_prosser. Senada dengan Prosser, pembocor ulung Evan Blass melalui akun Twitter dengan handle @evleaks juga memberikan petunjuk lain. Dalam sebuah render desain yang diduga parangkat Galaxy S21 FE, Blass mencantumkan twit berbunyi \"January 11th\". &nbsp;Tanggal itu kemungkinan merujuk pada waktu perilisan Galaxy S21 FE.', 'Gadget', 'pict1.png', '2021-12-24 02:12:16', NULL),
(31, 5, 'Foto Rupa Samsung Galaxy S22 Bocor di Media Sosial  Baca artikel CNN Indonesia \"Foto Rupa Samsung Galaxy S22 Bocor di Media Sosial\" selengkapnya di sini: https://www.cnnindonesia.com/teknologi/2021122', '<p>Jakarta, CNN Indonesia -- Bocoran tampilan Samsung Galaxy S22&nbsp;akhirnya terungkap. Ponsel tiruan atau dummy dari smartphone itu diungkap oleh penjual aksesoris asal Inggris, Mobile Fun.<br />Pada bocoran tampilan Galaxy S22 Series, terlihat ada tiga pilihan flagships itu. Ada Galaxy S22 berukuran 6,06 inci, Galaxy S22+ 6,55 inci, dan Galaxy S22 6,8 inci.<br />Galaxy S22 Ultra akan disertai S Pen yang disematkan di bodi ponsel, sama seperti seri Galaxy Note. Faktanya, bentuk dan tampilan keseluruhan dari dummy Galaxy S22 Ultra tampak sangat mirip dengan model Note.<br /><br />Mobile Fun telah mendaftarkan Galaxy S22 Ultra S Pen, yang akan tersedia dalam warna Hitam, Putih, Merah, dan Hijau. Kemungkinan pilihan warna tersebut merupakan varian yang akan disuguhkan.<br /><br />Galaxy S22 memiliki susunan kamera baru dengan lensa yang menonjol langsung dari panel belakang. Ini adalah bocoran yang menarik dari ponsel andalan Samsung baru-baru ini.<br /><br />Samsung belum secara resmi mengumumkan Galaxy S22 di pasar global. Namun belakangan ini seorang leaker kenamaan, Jon Prosser melaporkan bahwa Samsung akan menunda acara Unpacked untuk mengumumkan ponsel andalannya karena masalah rantai pasokan.<br /><br />Peluncuran Samsung Galaxy S22 diharapkan rilis tak jauh dari bocoran rilis, dan jika hal itu terjadi, maka flagship itu diharap masuk ke pasaran pada 9 Februari mendatang.<br /><br />(can/fjr)<br /><br />Baca artikel CNN Indonesia \"Foto Rupa Samsung Galaxy S22 Bocor di Media Sosial\" selengkapnya di sini:&nbsp;<a href=\"https://www.cnnindonesia.com/teknologi/20211224083045-185-738133/foto-rupa-samsung-galaxy-s22-bocor-di-media-sosial\">https://www.cnnindonesia.com/teknologi/20211224083045-185-738133/foto-rupa-samsung-galaxy-s22-bocor-di-media-sosial</a>.<br /><br />Download Apps CNN Indonesia sekarang https://app.cnnindonesia.com/</p>', 'Gadget', '61c53ec84b9cb.jpeg', '2021-12-24 03:30:16', NULL),
(32, 5, 'Terinspirasi dari Kemampuan Bunglon, Palit Hadirkan Desain Terbaru RTX 3060 Ti', '<p>Salah satu brand GPU asal Tiongkok yakni Palit, pada akhir bulan November kemarin baru saja mengumumkan sebuah desain GPU terbaru untuk RTX 3060 Ti mereka. Desain terbaru ini nampaknya terinspirasi dari bunglon yang memiliki sebuah kemampuan untuk berubah warna kulitnya.&nbsp;<br /><br />Desain RTX 3060 Ti teranyar ini, mereka beri nama&nbsp;<a href=\"https://www.palit.com/event/promote/2021/colorpop_3060ti/\">ColorPOP</a> yang diumumkan melalui situs resmi juga sekaligus pada channel YouTube mereka. <a href=\"https://youtu.be/0-C5AjDqxcc\">https://youtu.be/0-C5AjDqxcc</a></p>\r\n<p>Bila kalian lihat melalui video teranyar di atas, desain GPU terbaru mereka sangatlah mirip seperti kemampuan pada bunglon. Karena ketika kalian melihat dari suatu sisi, warna pada GPU tersebut akan berubah menjadi campuran dari violet, biru atau hijau.&nbsp;<br /><br />RTX 3060 Ti milik Palit ini memiliki spesifikasi yang sangat mirip seperti RTX 3060 Ti versi&nbsp;<em>founders edition,&nbsp;</em>di antaranya seperti&nbsp;<em>base clock&nbsp;</em>1410MHz,&nbsp;<em>boost clock&nbsp;</em>1665MHz, VRAM 8GB GDDR6, dan&nbsp;<em>CUDA Cores&nbsp;</em>sebanyak 4864.&nbsp;</p>\r\n<p>Uniknya, bila kita bandingkan dengan versi&nbsp;<em>founder edition&nbsp;</em>milik NVIDIA, RTX 3060 Ti milik Palit memiliki TDP yang sedikit berbeda dibandingkan NVIDIA. Yakni Palit memerlukan 220W, sedangkan NVIDIA memerlukan 200W, lalu pada bagian&nbsp;<em>power connector&nbsp;</em>pun Palit menggunakan 2&times;8&nbsp;<em>p</em><em>in Power&nbsp;</em><em>connector,</em>&nbsp;NVIDIA memerlukan 1&times;12&nbsp;<em>pin Power Connector</em>.</p>\r\n<p>Sayangnya, pada saat Palit mengumumkan RTX 3060 Ti ColorPOP mereka hingga saat ini belum ada kabar apakah mereka akan membawa desain GPU teranyar mereka menuju Indonesia. Mengingat mereka sendiri baru saja mengumumkan GPU tersebut pada tanggal 29 November yang lalu.&nbsp;</p>\r\n<p>Perlu diingat, ketika RTX 3060 Ti ColorPOP telah tiba di Indonesia, ada kemungkinan harga GPU tersebut akan langsung meroket, mengingat sampai saat ini harga GPU di Indonesia masih terbilang sangat tinggi.&nbsp;</p>\r\n<p><em>Baca lebih lanjut tentang&nbsp;<a href=\"https://gamebrott.com/?s=nvidia&amp;login=1\">NVIDIA</a>, dan juga ikuti berita-berita lainnya seputar Video Game bersama saya,&nbsp;<a href=\"https://gamebrott.com/author/montirmonyet?swcfpc=1&amp;login=1\">Daffa Dhiya.</a>&nbsp;</em>For press release and further collaboration, Contact me at&nbsp;<strong>author@gamebrott.com</strong></p>\r\n<p><strong>sc :&nbsp;</strong><a href=\"https://gamebrott.com/terinspirasi-dari-kemampuan-bunglon-palit-hadirkan-desain-terbaru-rtx-3060-ti\">Terinspirasi dari Kemampuan Bunglon, Palit Hadirkan Desain Terbaru RTX 3060 Ti - Gamebrott.com</a></p>', 'Komputer & PC', '61c5410bcf3e0.jpg', '2021-12-24 03:39:55', NULL),
(33, 4, 'Inikah Tanggal Peluncuran Samsung Galaxy S21 FE? ', 'Sekian lama nasibnya tak kunjung jelas, kini tanda-tanda kehadiran <strong>Galaxy S21 FE</strong> (<em>Fan Edition</em>) kian menguat. Belakangan, berembus kabar yang mengungkap tanggal peluncuran ponsel versi \"murah\" dari lini Galaxy S21 ini. <br /><br />Salah satu kabar tersebut dibagikan oleh, Jon Prosser, seorang pembocor gadget kenamaan yang kerap membeberkan informasi terkait smartphone yang akan dirilis di pasaran. <br /><br />Melalui akun Twitter pribadinya dengan handle @jon_prosser, ia mengungkap detail informasi seputar tanggal peluncuran Galaxy S21 FE. <br /><br />Menurut Prosser, Samsung disinyalir akan mengumumkan kehadiran Galaxy S21 FE pada 3 Januari pukul 18.00 PST atau 4 Januari 09.00 pagi apabila dikonversi ke satuan Waktu Indonesia Bagian Barat (WIB). <br /><br />Meski demikian, waktu tersebut terlihat janggal karena tidak selaras dengan perkiraan mulainya sesi keynote Samsung di Customers Electronics Show (CES) 2022 yang akan dilaksanakan pada 4 Januari 2022 18.30 PST (sekitar 5 Januari 09.30 WIB). <br /><br />Sebelumnya, terdapat indikasi kuat yang menyebut bahwa informasi seputar Galaxy S21 FE akan diumumkan melalui acara pameran teknologi akbar, CES 2022 yang rencananya akan digelar 5-8 Januari 2022 di Las Vegas, Amerika Serikat. <br /><br />Selain membeberkan indikasi tanggal peluncuran perangkat, Prosser turut mengungkap jadwal penjualan perdana Galaxy S21 FE yang konon akan pada digelar pada 11 Januari 2022. Apabila mengacu pada posting awal yang diunggah Prosser, maka Galaxy S21 FE diduga akan dijual secara langsung tanpa harus didului sesi pemesanan awal (pre-order). \"Saya mendengar bahwa pengumuman untuk S21 FE telah dipindahkan ke Senin, 3 Januari @6 sore PST. <br /><br />Ketersediaan umum masih pada 11 Januari,\" tulis akun Twitter @jon_prosser. Senada dengan Prosser, pembocor ulung Evan Blass melalui akun Twitter dengan handle @evleaks juga memberikan petunjuk lain. Dalam sebuah render desain yang diduga parangkat Galaxy S21 FE, Blass mencantumkan twit berbunyi \"January 11th\". &nbsp;Tanggal itu kemungkinan merujuk pada waktu perilisan Galaxy S21 FE.', 'Gadget', 'pict1.png', '2021-12-23 19:12:16', NULL),
(34, 6, 'Kode Komputer Wajib Diketahui', '<img src=\"http://localhost/techcorner/forum/assets/upload/60797_kom1.jpg\" alt=\"\" width=\"540\" height=\"382\" /><br /><br />Pada perkembangan zaman yang telah pesat Komputer menjadi salah satu alat yang banyak digunakan untuk mencari berbagai informasi yang ada di internet.<br /><br />Pada pelajar komputer sendiri memiliki banyak kegunaan diantaranya adalah dapat digunakan untuk mengerjakan tugas-tugas dengan kreatif karena kecanggihan teknologi yang mana komputer dapat menampilkan berbagai macam teks yang menarik, adanya warna, gerak, suara, gambar, dan banyak hal lainnya. Hal tersebut semakin mendukung pelajar untuk mengembangkan pengetahuan serta keterampilan yang ada dalam diri.<br /><br />Beberapa kode dalam komputer yang perlu diketahui:<br /><br />1. Ctrl + B<br />kode tersebut digunakan untuk menebalkan tulisan yang diinginkan, dan sebelum itu kalian perlu blok terlebihdahulu tulisan mana yang ingin kalian tebalkan.<br /><br />2. Ctrl + C<br />Kode ini digunakan untuk menyalin atau copy tulisan.<br /><br />3. Ctrl + U<br />Untuk memberi garis bawah pada tulisan kode tersebut dapat digunakan karena fungsi dari kode tersebut adalah untuk memberi garis bawah pada tulisan yang diperlukan.<br /><br />4. Ctrl + I<br />Kode ini memiliki fungsi untuk memiringkan tulisan.<br /><br />5. Ctrl + N<br />Untuk membuka jendela atau tab kode ini dapat menjadi kunci mudah untuk kalian lakukan.<br /><br />6. Ctrl + A<br />Kode tersebut dapat digunakan untuk memblokir seluruh tulisan atau teks pada file.<br /><br />7. Ctrl + F4<br />Berfungsi untuk menutup jendela dokumen sekaligus untuk menutup aplikasi. Kode Ctrl + F4 menjadi langkah cepat dan sangat mudah untuk dilakukan.<br /><br />8. Ctrl + F<br />Terkadang mencari file dan membuka menu dan pencarian kata sulit untuk dilakukan. Akan tetapi, kode Ctrl + F dapat dijadikan sebagai rahasia mudah untuk melakukan hal tersebut.<br /><br />9. Ctrl + Z<br />Untuk membatalkan perintah sebelumnya kalian dapat menggunakan kode ini.<br /><br /><br />Nah kode-kode tersebut memiliki manfaat dan harus diingat ya.<br /><br />Terima kasih', 'Komputer & PC', '61c532467283b.jpg', '2021-12-23 19:36:54', '2021-12-24 9:42 am'),
(35, 6, 'Apa Itu Magnetic Disk? ', '<img src=\"http://localhost/techcorner/forum/assets/upload/45108_kom3.jpg\" alt=\"\" width=\"540\" height=\"360\" /><br /><br /><br />PENGERTIAN DEFINISI MAGNETIC DISK<br />Dalam sistem komputer, komputer memiliki beberapa komponen yang penting seperti CPU, GPU, dan storage. Dalam pembahasan kali ini saya akan membahas tentang magnetic disk, magnetik disk ini termasuk dalam kategori storage atau dalam bahasa nya yaitu penyimpanan yang terdapat pada sistem komputer, untuk lebih jelasnya kita simak pembahasan berikut ini.<br />Apa itu Magnetic disk ?<br /><br />Magnetic disk atau dalam bahasa Indonesia di sebut dengan penyimpanan magnet dan orang Indonesia menyebut nya dengan harddisk atau HDD, merupakan penyimpanan yang digunakan untuk menyimpan data file pada sistem komputer bisa berubah file dokumen, foto, video, suara dan lain-lainnya.<br /><br />Jenis penyimpanan ini biasa kita temukan pada komputer modern saat ini, dan penyimpanan jenis ini berbeda dengan penyimpanan sistem komputer lainnya karena cara kerja pada penyimpanan magnet ini mirip seperti piringan hitam beserta alat pemutar nya yaitu vinyl player dalam bentuk ukuran yang lebih compact namun tidak bisa mengeluarkan suara secara langsung.<br /><br />Untuk pengenalannya penyimpanan ini dibagi menjadi beberapa bagian yaitu:<br /><br />Spindle merupakan pusat putaran pada magnetic diks ini berupa kepingan-kepingan cakram magnetik yang berputar sangat cepat.<br />Cakram magnetik merupakan piringan berbentuk plat tipis yang berbentuk seperti CD terbuat dari logam ataupun plastik dan di permukaanya dilapisi bahan yang dapat dimagnetisasi.<br />Read-write Head merupakan mekanisme sebagai perantara yang digunakan untuk membaca dan menulis pada cakram/ piringan.<br />Enclosure merupakan lapisan luar yang digunakan untuk melindungi komponen-komponen magnetic disk dari benturan, percikan air dan debu.<br />Interfacing Module merupakan sebuah rangkaian perangkat elektronik yang digunakan dalam menjalankan data dari head untuk membaca dan menulis data. Teknologi interfacing module yang digunakan sekarang ini yaitu teknologi serial SATA, hal ini dikarenakan untuk mengantikan hardisk ATA yang lamban di bandingkan dengan hardisk SATA.<br />Kesimpulan-nya magnetic disk &nbsp;atau hardisk ini merupakan sebuah alat penyimpanan yang digunakan sistem komputer untuk menyimpan data baik itu dalam bentuk file, foto, video dan lainnya. Serta teknologi yang digunakan hardisk saat itu menggunakan teknologi serial SATA yang lebih cepat dalam memproses menulis dan membaca data, dan secara tidak langsung mengantikan teknologi hardisk ATA.<br />Cukup sekian artikel yang bisa saya tulis, bila ada kesalah dalam perkataan, kurang lebih mohon maaf dan terima kasih telah membaca.', 'Laptop / Notebook', '61c53a378f4e5.jpg', '2021-12-23 20:10:47', NULL),
(36, 7, 'LG Umumkan Laptop Gaming Pertamanya, UltraGear 17G90Q', 'Perusahaan elektronik asal Korea Selatan, LG akhirnya mengumumkan kehadiran laptop gaming tipis pertamanya yang mengusung nama UltraGear 17G90Q.Dari segi desain, bodi UltraGear 17G90Q dibalut dengan casing berbahan aluminium yang memiliki ketebalan 21,4 mm dan bobot berkisar 2,64 kg.Laptop ini memiliki panel layar IPS LCD berukuran 17,3 inci (1.920 x 1.080 piksel) yang mendukung refresh rate hingga 300 Hz dengan waktu respons yang diklaim mencapai 1 ms, beserta cakupan sRGB sebesar 99 persen.<br />Pada aspek hardware, UltraGear 17G90Q ditenagai CPU Intel Tiger Lake H generasi ke-11 yang disertai pengolah grafis NVIDIA GeForce RTX 3080 Max-Q. Adapun prosesor tersebut turut dipadu dengan dua opsi memori RAM DDR4 yang terdiri dari 16 GB dan 32 GB, serta penyimpanan SSD M.2 berkapasitas 1 TB. Untuk menunjang kebutuhan gaming, laptop ini dibekali dengan sistem pendinginan yang memanfaatkan teknologi vapor chamber. Ada pula software UltraGear Studio untuk mengontrol kinerja sistem, kecepatan kipas, dan pencahayaan lampu pencahayaan RGB yang terdapat pada keyboard.<br />Di sisi koneksivitas, UltraGear 17G90Q dilengkapi satu buah port USB 4 Gen 3x2 Type-C yang mendukung Thunderbolt 4, satu buah port USB-C 3.2 2x1. dan dua buah port USB 3.2 Gen 2x1.<br />Lalu terdapat sebuah port HDMI dan ethernet, satu buah slot microSD, serta satu buah port jack 3.55 mm dan RJ45. Sebagaimana dihimpun KompasTekno dari GSM Arena, Rabu (22/12/2022), sektor daya UltraGear 17G90Q ditopang dengan baterai berkapasitas 93 watt-hours (Whr). Fitur lain yang dimiliki laptop ini mencakup pemindai sidik jari yang terintegrasi dengan tombol daya, webcam FHD, mikrofon ganda, kamera IR yang terintegrasi dengan Windows Hello, Wi-Fi 6, dan stereo speakers DTS X Ultra.<br />Untuk ketersediaan, UltraGear 17G90Q hadir dalam satu varian warna, yakni Purple Grays. Laptop gaming ini direncanakan bakal meluncur secara perdana di AS dan Korea Selatan pada awal 2022 mendatang. Meski demikian, hingga saat ini LG masih belum mengungkap harga dari UltraGear 17G90Q. Informasi tersebut agaknya baru akan dipublikasikan dalam ajang pameran elektronik tahunan Customers Electronics Show (CES 2022) yang akan digelar pada 4-5 Januari 2022 mendatang di Las Vegas, Amerika Serikat.', 'Laptop / Notebook', '61c546a840230.jpg', '2021-12-24 04:03:52', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posting`
--
ALTER TABLE `posting`
  ADD PRIMARY KEY (`id_thread`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posting`
--
ALTER TABLE `posting`
  MODIFY `id_thread` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
